# Generated by Django 3.2.9 on 2021-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500)),
                ('address', models.CharField(default=None, max_length=1000)),
                ('venue_image', models.CharField(default=None, max_length=1000)),
                ('capacity', models.CharField(default=None, max_length=1000)),
            ],
        ),
    ]
