# Generated by Django 3.2.9 on 2021-12-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='about',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
