# Generated by Django 3.2.9 on 2021-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
