# Generated by Django 3.2.9 on 2021-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=500)),
                ('description', models.CharField(default=None, max_length=1000)),
                ('date', models.CharField(default=None, max_length=100)),
                ('photo', models.CharField(default=None, max_length=1000)),
                ('location', models.CharField(default=None, max_length=500)),
                ('start_time', models.CharField(default=None, max_length=100)),
                ('finish_time', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
