# Generated by Django 3.2.9 on 2021-12-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_capacity'),
        ('categories', '0002_alter_category_category'),
        ('events', '0004_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finish_time',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(blank=True, to='venues.Venue'),
        ),
    ]
