# Generated by Django 3.2.9 on 2021-12-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_capacity'),
        ('categories', '0002_alter_category_category'),
        ('events', '0008_auto_20211206_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='categories.Category'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(blank=True, null=True, to='venues.Venue'),
        ),
    ]
