# Generated by Django 3.2.9 on 2021-12-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_category'),
        ('venues', '0002_alter_venue_capacity'),
        ('events', '0009_auto_20211206_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(blank=True, to='venues.Venue'),
        ),
    ]
