# Generated by Django 3.2.9 on 2021-12-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_venue_capacity'),
        ('categories', '0002_alter_category_category'),
        ('events', '0010_auto_20211206_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Category'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='venues.venue', verbose_name='Venue'),
        ),
    ]
