# Generated by Django 3.2.9 on 2021-12-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20211206_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish_time',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
