# Generated by Django 4.0 on 2022-01-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish_time',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
